# theme: jekyll-theme-minimal
theme: jekyll-theme-cayman
title: HOPID
description: Heterogeneous Prompt-Guided Entity Inferring and Distilling for Scene-Text Aware Cross-modal Retrieval
github:
  is_project_page: false

  aaai25-HOPID/hopid.github.io